### ISSUE TITLE
OSを再インストールしたとき、cookieを復号できないことがある？

### ISSUE THREAD

**Issue by Toukotsu** [namoshika/SnkLib.App.CookieGetter#3]
長文失礼します。
少し気になる挙動がありましたのでご報告まで。

数日前、Win8.1が不機嫌だったので再インストールをしたのですが、
cookie含むユーザデータをそのままバックアップしていたせいか、
\Net4.5\SnkLib.App.CookieGetter\Utility.cs(101) の
Win32.CryptUnprotectData() で失敗していました。
失敗したターゲットはSleipnir(3|5)/OperaのBlinkだったようです。

FirefoxやIEの設定はバックアップしていなかったようで不明です。
chromeは使ってませんでしたすいません。

ただ、対象のcookieすべてが読めなくなるわけではなく、
今回は nicovideo.jp の "/" など、一部だけが復号できなくなっていました。
Sleipnir/Opera で nicovideo.jp のcookieを削除し、
再度ログインしなおしたところ正常に復号できました。

今回、Sleipnir側では正常にログインできているのに
CookieGetterでAssertにかかってしまったため、報告しました。

正直こんな操作するほうが珍しいかもしれませんが、
認識しない！というユーザももしかしたら発生するかもしれません。

あまり問題にならなそうであればこのissueはCloseしてもらえればと思います。

**Comment by namoshika** [comment]
報告ありがとうございます。
この挙動に関しては、どうしようもない気がします。

* **報告されている挙動の原因は、**
  CryptUnprotectDataの新環境における暗号鍵が旧環境と異なるためだと思われます。このAPIは再インストールでchromeのcookiesのみ旧環境から持ってきたりすると復号化に失敗します。この挙動に関しては私の環境でも確認できました。また、Assertの挿入に関してもchromeの仕様変更や動作環境側の異常を察知するために入れているコードであるため、除去するわけにはいかないです。

* **"/"が復号できていない件は、**
  "http://nicovideo.jp" が "http%3A%2F%2Fnicovide.jp" などと表示されているならば、これはURLエンコードです。元のcookieファイルレベルでああいう形式な保存がされています。これの事でしょうか?

以上の点で仕様ではないかと...(｀・ω・´)

参考
* [Win32] Encryption via Data Protection API (DPAPI)
  https://msmania.wordpress.com/tag/cryptprotectdata/

* URIエンコード
  [http://e-words.jp/w/URLエンコード.html](http://e-words.jp/w/URL%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89.html)

**Comment by Toukotsu** [comment]
なるほど、再インストールで暗号鍵が変わるのか…確かに言われてみれば納得です。
"/"については、暗号鍵の問題かと思われます。
"/"以外にもnicovideo.jpのcookieだけで6件ほど復号に失敗していたうえ、
一度削除すると正常に動作するようになったのでエンコードなどは問題ないはずです。

ただ、Trace.Assert を呼び出したい旨については、エラーテキストに
復号できなかったブラウザ名を表示したほうがいいかもしれません。
Trace.Assert を呼ぶ場合、実行する親アプリの動作に関わらずダイアログが表示されていますが、
Sample のように同時にすべてのブラウザをチェックしに行くと、
どのブラウザで問題が発生したかわからず対処しづらい状態が発生してしまいます。
今回はエラーメッセージに BlinkCookieImporter から呼び出された旨あったので
Blinkを使用したすべてのブラウザのCookieを削除することで復帰できましたが、
一般にBlinkと言われて判断できるとは言い難いと思いますし、
エラーメッセージ出た時点でお手上げってユーザも少なくないかと思います。
しかし DecryptProtectedData() 内にブラウザ情報が渡ってきてないためすこし厄介ですね。
…いやトレースログを解析すればあるいは…?

**Comment by namoshika** [comment]
とりあえず思いつく範囲で対処しました。

* CryptUnprotectData失敗時に一部だけが復号できなくなっているパターンの再現が出来なかったのが気になりますが、復号出来ないのが正常挙動な様子ですので仕様とします。

* エラーメッセージの方は考えた結果としてAssert除去し、代わりに挙動チェックアプリとしてLibCheckerを付けました。こちらの方がログなどを出せます。
